// ============================================
// OFERTAS DE TRABAJO - FÁCIL DE REPLICAR
// ============================================
// Para agregar una nueva oferta:
// 1. Copia uno de los objetos de abajo
// 2. Pégalo en el array 'jobOffers'
// 3. Cambia todos los datos
// 4. Cambia el 'id' a un número único (job-003, job-004, etc.)
// ============================================

export interface JobOffer {
  id: string
  title: string
  company: string
  location: string
  country: string
  salary: string
  salaryPerHour?: string
  contractType: string
  duration: string
  requirements: string[]
  benefits: string[]
  description: string
  available: boolean
  urgent?: boolean
}

// ARRAY DE OFERTAS - FÁCIL DE MODIFICAR Y REPLICAR
export const jobOffers: JobOffer[] = [
  {
    id: 'job-001',
    title: 'Operario de Producción',
    company: 'Empresa Logística Holandesa',
    location: 'Ámsterdam',
    country: 'Países Bajos',
    salary: '€2,480 - €2,800/mes',
    salaryPerHour: '€15.50/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Disponibilidad inmediata',
      'Inglés básico (B1)',
      'Experiencia en logística (deseable)',
    ],
    benefits: [
      'Alojamiento incluido',
      'Transporte proporcionado',
      'Seguro médico',
      'Capacitación incluida',
    ],
    description: 'Buscamos operarios para trabajar en almacén logístico. Trabajo en equipo, ambiente internacional, horarios flexibles. Ideal para personas responsables y con ganas de trabajar.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-002',
    title: 'Personal de Almacén',
    company: 'Centro de Distribución',
    location: 'Rotterdam',
    country: 'Países Bajos',
    salary: '€2,500 - €2,900/mes',
    salaryPerHour: '€15.75/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Disponibilidad inmediata',
      'Inglés funcional',
      'Buena condición física',
    ],
    benefits: [
      'Alojamiento compartido incluido',
      'Bicicleta eléctrica para transporte',
      'Bonos por productividad',
      'Posibilidad de extensión',
    ],
    description: 'Oportunidad en centro de distribución moderno. Trabajo dinámico, equipo multicultural, excelente ambiente laboral. Perfecto para parejas que quieren trabajar juntos.',
    available: true,
    urgent: true,
  },
  {
    id: 'job-003',
    title: 'Conductor de Reparto',
    company: 'Empresa de Retail Online',
    location: 'Países Bajos',
    country: 'Países Bajos',
    salary: '€2,400 - €2,800/mes',
    salaryPerHour: '€17.46/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Licencia de conducir europea categoría B vigente',
      'Inglés básico comunicación',
      'Teléfono con SIM y crédito para contacto',
      'Buena condición física (escaleras, levantar peso, entrar y salir del vehículo)',
      'Vestimenta: jeans requeridos (no joggers, sudaderas, jeans rotos)',
      'Aspecto amigable y actitud orientada al cliente',
      'Certificado de buena conducta (VOG)',
      'Entrevista por video obligatoria',
    ],
    benefits: [
      'Bono WUK semanal',
      'Bonos por turnos nocturnos y fines de semana',
      'Garantía de 28 horas semanales (posibilidad de más horas)',
      'Alojamiento organizado por la agencia',
      'Ubicación de bicicleta garantizada en 99% de los casos',
      'Seguro médico completo cubierto',
      'Entrenamiento 1 a 1 con instructor (3 días)',
      'Ambiente familiar y equipo de apoyo',
      'Vehículos modernos con sistema de navegación',
    ],
    description: 'Únete al equipo de reparto online. Conduce una furgoneta (hasta 3.5t) en ciudades y pueblos pequeños. Entrega de cestas y cajas de productos retail a clientes. Comunicación amigable y profesional con clientes. Navegación mediante dispositivo Zebra con Android y Google Maps. Seguimiento de horarios de entrega y procedimientos de la empresa. Trabajo físicamente exigente con 20-25 clientes por viaje.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-004',
    title: 'Operario de Almacén Logístico',
    company: 'Centro de Distribución Médico',
    location: 'Waalwijk, Venray, Roosendaal, Nieuwegein, Heerlen, Eindhoven, Oostrum',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€15.60/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Certificado de antecedentes penales (VOG) obligatorio',
      'Inglés básico comunicación (probado en sitio)',
      'Buena atención al detalle y gestión del tiempo',
      'Buena condición física sin problemas de espalda',
      'Disposición para trabajar en carga y conducción de maquinaria',
      'Estancia mínima de 6 meses',
      'Flexibilidad con turnos y horas extras',
      'Sin tatuajes en cara o cuello, sin piercings faciales',
      'Experiencia con maquinaria logística o montacargas (ventaja)',
      'Licencia de montacargas (NL o convertible de otro país)',
    ],
    benefits: [
      'Trabajo estable a largo plazo',
      'Oportunidades de capacitación y certificación',
      'Pago semanal y vacaciones pagadas',
      'Ambiente de trabajo internacional y de apoyo',
      'Bonos por turnos nocturnos, fines de semana y horas extras',
      'Transporte siempre organizado por la agencia',
      'Bicicleta o bicicleta eléctrica según distancia',
      'Seguro médico disponible',
    ],
    description: 'Únete a un importante centro de distribución especializado en productos médicos y del hogar. Asignación a uno de los cinco departamentos principales: VAS In/Outbound, Picking Packing, o Shipping. Tareas incluyen carga/descarga de contenedores, operación de maquinaria logística (entrenamiento proporcionado), picking y packing con escáneres, clasificación, etiquetado y escaneo de paquetes. Primer día incluye entrenamiento de seguridad pagado y distribución de ropa y calzado de seguridad.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-005',
    title: 'Operario de Almacén Internacional',
    company: 'Centro Logístico Internacional',
    location: 'Beringe',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€15.60/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Certificado de buena conducta (VOG) requerido',
      'Inglés básico comunicación',
      'Buena condición física para trabajo de pie, caminar y levantar hasta 20 kg',
      'Disponibilidad para rotación de 3 turnos',
      'Seguimiento de reglas de seguridad BHV',
      'Calzado de seguridad obligatorio',
      'Pantalones largos (no leggings, monos, sudaderas)',
      'Camiseta que cubra hombros y vientre',
      'Completar e-learning obligatorio de DHL antes del primer día',
    ],
    benefits: [
      'Oportunidades de crecimiento y certificación',
      'Entrenamiento con compañero asignado durante los primeros días',
      'Bonos por turnos nocturnos, fines de semana y horas extras',
      'Ambiente con temperatura regular (no refrigerado)',
      'Cantinas disponibles con máquinas expendedoras, microondas y neveras',
      'Té, café y agua gratis',
      'Casilleros individuales proporcionados',
      'Proceso de incorporación pagado por DHL',
    ],
    description: 'Únete a uno de los equipos de logística más grandes del mundo, presente en más de 220 países. En Beringe formarás parte del equipo que maneja paquetes internacionales. Responsabilidades incluyen clasificación y picking de paquetes con escáner manual, reempaque, carga y descarga de camiones, control de calidad y medición, escaneo y empaque de mercancías. Posibilidad de entrenamiento en EPT, montacargas, clasificación de paquetes de tamaño irregular y otras operaciones logísticas.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-006',
    title: 'Operario de Almacén Postal',
    company: 'Centro de Procesamiento Postal',
    location: 'Oirschot, Veenendaal',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€15.60/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Inglés básico comunicación',
      'Buena condición física para trabajo de levantamiento y de pie',
      'Disposición para trabajar en diferentes turnos (tarde, noche, fin de semana)',
    ],
    benefits: [
      'Plan de trabajo semanal estable y regular',
      'Soporte diario de coach flexible en el piso de trabajo',
      'Contacto personal y digital con persona de contacto de la agencia',
      'Pagos semanales puntuales y horas de trabajo garantizadas',
      'Proceso de reclutamiento online',
      'Cantina con sopa y leche con chocolate gratis',
      'Agua embotellada, paños refrescantes y aire acondicionado en almacén',
      'Alojamiento organizado a distancia de bicicleta del almacén',
      'Seguro médico organizado por la agencia',
      'Bonos por tardes, noches y fines de semana',
    ],
    description: 'Únete a una de las empresas postales más grandes del mundo, en constante innovación y expansión. En sus almacenes se procesan cientos de cartas y paquetes diariamente. Responsabilidades incluyen carga y descarga de contenedores, clasificación, verificación de calidad y etiquetado de paquetes, manejo de paquetes de diferentes tamaños (desde gramos hasta 50 kg), trabajo en parejas para levantamiento pesado. Trabajo de lunes a viernes en turnos de tarde, noche y posible trabajo de fin de semana con bonos adicionales.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-007',
    title: 'Operario de Almacén Logístico',
    company: 'Centro Logístico Moderno',
    location: 'Venlo, Maastricht, Nistelrode',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€14.40/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Certificado de antecedentes penales del país de origen (emitido dentro de 6 semanas antes del inicio)',
      'Inglés básico comunicación',
      'Buena condición física y capacidad para manejar tareas repetitivas',
      'Capacidad para trabajar en ambiente dinámico y rápido',
      'Disponibilidad para trabajo por turnos',
      'Licencia de montacargas o reachtruck (ventaja)',
    ],
    benefits: [
      'Progresión salarial basada en experiencia y licencias',
      'Trabajo con marcas internacionales reconocidas de moda, cosméticos y calzado',
      'Almacén moderno con tecnología avanzada y automatización',
      'Alojamiento disponible (consultar costos)',
      'Seguro médico disponible (consultar costos)',
      'Transporte: alquiler de bicicleta o vehículo de empresa según distancia',
      'Sin depósito requerido',
      'Pago semanal',
      'Bonos adicionales diarios para conductores',
    ],
    description: 'Oportunidad en uno de los almacenes más grandes y modernos de la región. Trabajamos con marcas reconocidas de moda, cosméticos y calzado. Tareas incluyen empaque de ropa, cosméticos, carteras, calzado y otros productos, kitting, reempaque, reetiquetado, picking de pedidos y ensamblaje de productos, manejo cuidadoso de devoluciones, uso de sistemas automatizados como pick-by-light y líneas de empaque automáticas, tareas físicas (levantar hasta 10 kg). Trabajo organizado en dos turnos.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-008',
    title: 'Conductor de Maquinaria Logística',
    company: 'Centro de Distribución Tecnológica',
    location: 'Venray',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€14.40/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Inglés básico comunicación',
      'Habilidades básicas de computación',
      'Certificados de maquinaria (Reach Truck, Heftruck o EPT)',
      'Flexibilidad para trabajar horas extras, fines de semana y festivos',
      'Disposición para aceptar nuevas oportunidades de capacitación',
      'Disposición para realizar tareas diferentes a picking cuando sea necesario',
      'Alojamiento propio requerido',
    ],
    benefits: [
      'Posición de tiempo completo a largo plazo con empresa reconocida',
      'Oportunidades para desarrollar habilidades y avanzar dentro de la empresa',
      'Ambiente de equipo vibrante, divertido y de apoyo',
      'Trabajo en ambiente limpio y organizado con productos de última generación',
      'Horario balanceado de trabajo-vida personal',
      'Turnos regulares de día',
    ],
    description: 'Buscamos personas apasionadas para unirse como conductores de EPT en una empresa logística. Si buscas una oportunidad a largo plazo en un ambiente dinámico y gratificante, queremos conocerte. Asegurarás el funcionamiento fluido y eficiente del departamento, manejando productos de alta tecnología incluyendo pantallas, monitores, dispositivos de seguridad, escáneres telescópicos y más. Realizarás controles de calidad para garantizar que todos los productos cumplan con los más altos estándares.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-009',
    title: 'Operador de Montacargas',
    company: 'Instalación Logística Especializada',
    location: 'Venray',
    country: 'Países Bajos',
    salary: '€2,400 - €2,600/mes',
    salaryPerHour: '€15.03/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Fuertes habilidades de comunicación en inglés',
      'Capacidad para trabajar bajo presión y manejar prioridades cambiantes',
      'Experiencia con WMS (Sistema de Gestión de Almacén) es una ventaja',
      'Conocimientos básicos de computación',
      'Certificación válida de reachtruck',
      'Flexibilidad para trabajar turnos, fines de semana y festivos según necesidad',
      'Disposición para recibir capacitación adicional',
      'Alojamiento propio requerido',
    ],
    benefits: [
      'Posición de tiempo completo a largo plazo (mínimo 32 horas semanales)',
      'Ambiente de trabajo dinámico y agradable',
      'Pago competitivo',
      'Oportunidades de empleo a largo plazo y crecimiento profesional',
      'Empresa de apoyo que valora tu contribución',
      'Horario de trabajo estable',
    ],
    description: '¿Te interesa un rol como conductor de reachtruck en una gran empresa logística ubicada en Venray? Buscamos individuos motivados para formar parte de nuestro equipo. Operarás eficientemente el reachtruck dentro del departamento mientras te adhieres a todos los procedimientos de la empresa. Mantendrás altos estándares de rendimiento, incluyendo puntualidad, calidad y productividad, ayudando a reducir los costos departamentales.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-010',
    title: 'Especialista en Operaciones Logísticas',
    company: 'Compañía de Distribución Internacional',
    location: 'Venlo',
    country: 'Países Bajos',
    salary: '€2,300 - €2,400/mes',
    salaryPerHour: '€14.40 - €15.00/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Hablas y comprendes inglés o neerlandés',
      'Disponibilidad fulltime',
      'No te molesta trabajar en turno de día o por turnos',
      'Actitud activa y capacidad para asumir nuevas tareas rápidamente',
      'Perfil energético, con ganas de aprender y confiable',
    ],
    benefits: [
      'Salario competitivo según tu experiencia',
      'Bonos adicionales por trabajar en la tarde',
      'Reembolso de gastos de viaje y estacionamiento gratuito',
      'Contrato con perspectiva de empleo fijo con buen desempeño',
      'Mucho espacio para crecer, por ejemplo hacia coordinador o líder de equipo',
      'Capacitaciones y entrenamientos gratuitos para desarrollar habilidades logísticas',
      'Ambiente de trabajo informal donde todos se conocen y se ayudan',
      'Oportunidades para obtener certificados de heftruck, reachtruck o EPT',
    ],
    description: 'Comienza tu carrera como especialista en operaciones logísticas en Venlo. Ningún día es igual. Junto con tus colegas te asegurarás de que todos los bienes y paquetes lleguen a tiempo y al lugar correcto. Trabajarás en un empresa logística internacional que diariamente hace que millones de productos tengan un viaje seguro y rápido. Tareas incluyen recolección de pedidos, control y preparación para envío, etiquetado de productos con códigos de barras, trabajo con escáneres y sistemas modernos.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-011',
    title: 'Recolector y Empaquetador de Almacén',
    company: 'Centro de Procesamiento de Productos',
    location: 'Venlo',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€14.40 - €15.63/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Capacidad para manejar trabajo físico - peso promedio de caja es 8kg (rango: 1kg a 45kg)',
      'Fuerte espíritu de equipo y motivación son esenciales',
      'Conocimiento de neerlandés o inglés',
      'Mínimo 6 meses de experiencia en logística es preferido',
      'Importante: No se proporciona alojamiento, debes vivir cerca o tener tu propia vivienda y transporte',
      'Disposición para trabajar horas extras cuando sea necesario',
    ],
    benefits: [
      'Ambiente de trabajo dinámico y de apoyo',
      'Oportunidades de desarrollo y capacitación',
      'Ser parte de un proyecto en crecimiento con una marca global reconocida',
      'Trabajo a largo plazo con estabilidad',
      'Capacitación adicional disponible en Reachtruck, Heftruck, inbound o control de calidad',
      'Posibilidad de convertirse en empleado completo y ganar hasta 15.63 por hora',
    ],
    description: '¿Buscas una nueva oportunidad en logística con espacio para crecer? Estamos buscando individuos motivados para unirse a nuestro equipo. Comenzarás en el departamento de picking con oportunidad de transición al proceso de empaque basado en desempeño. Trabajarás con una variedad de productos incluyendo monitores, sillas y equipos de gaming. Ambiente de almacén dinámico donde podrás desarrollar múltiples habilidades.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-012',
    title: 'Recolector de Pedidos en Almacenes de Supermercados',
    company: 'Centro de Distribución Alimentaria',
    location: 'Venray',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€14.40/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Experiencia conduciendo EPT o disposición para certificarse',
      'Disposición para trabajar en diferentes zonas de temperatura',
      'Buena comunicación en inglés, neerlandés y/o polaco (depende de ubicaciones)',
    ],
    benefits: [
      'Pagos semanales cada martes',
      'Reclutamiento online con proceso simple y mínimas formalidades',
      'Seguro médico',
      'Contrato de trabajo bajo ley neerlandesa con horas garantizadas',
      'Alojamiento organizado y transporte al trabajo si lo necesitas',
      'Soporte 24/7 por nuestro centro de servicio',
      'Acceso a la app myOTTO con horario de trabajo, recibos de pago y preguntas frecuentes',
      'Oportunidades de desarrollo y crecimiento profesional',
    ],
    description: 'En los Almacenes de Supermercados trabajarás con conocidas tiendas online y centros de distribución de comestibles en todo el país. Trabajarás con productos de larga duración, congelados y frescos. Tu rol incluirá recolección de productos con sistema de picking manual o por voz, levantamiento de paquetes de diferentes pesos, empaque de todos los pedidos para envío, conducción de EPT o camión de recogida. Dependiendo de tu lugar de trabajo, podrás tener la opción de trabajar en turnos de día, tarde o noche.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-013',
    title: 'Empleado de Almacén en Instalación Deportiva',
    company: 'Centro Logístico de Artículos Deportivos',
    location: 'Heerlen',
    country: 'Países Bajos',
    salary: '€2,500 - €2,700/mes',
    salaryPerHour: '€15.60/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Listo para aprender y abierto a certificarse para EPT o reachtruck',
      'Flexibilidad para trabajar diferentes turnos',
      'No se requiere experiencia, pero si has trabajado en almacén antes, sería una gran ventaja',
      'Capacidad para comunicarse en inglés',
    ],
    benefits: [
      'Tarifa por hora atractiva con bonos de vacaciones',
      'Introducción y capacitación pagadas',
      'Bonos por trabajo en tarde, noche y fines de semana (hasta 100%)',
      'Oportunidades para crecer y entrenar para EPT, reachtruck o montacargas',
      'Ropa de trabajo proporcionada',
      'Alojamiento de calidad con transporte al trabajo',
      'Snacks, bebidas y cantina con comidas calientes',
      'Mesa de futbolín para descansos',
      'Mínimas formalidades - todo online',
      'Soporte 24/7 y app MyOTTO para horarios, recibos y cursos de idiomas',
    ],
    description: '¿Listo para unirte a un líder global en logística? Trabajamos con algunas de las marcas más icónicas del mundo. En uno de nuestros almacenes en Heerlen, todo se trata de deportes, desde ropa de moda hasta calzado y accesorios. Si te encanta estar activo y quieres un trabajo que te mantenga en movimiento, este es el lugar para ti. Tu rol incluirá recolección y empaque de pedidos, control de calidad, etiquetado de paquetes y manejo de devoluciones, escaneo, sellado y envío, clasificación de artículos, trabajo manual con ropa, levantamiento de paquetes y cajas de diferentes pesos.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-014',
    title: 'Operario de Almacén Multilocalización',
    company: 'Empresa de Servicios Logísticos',
    location: 'Venray, Amsterdam, Roosendaal, Born, Den Haag, Eindhoven, Heerlen, Bleiswijk, Waalwijk, Nieuwegein, Nijmegen',
    country: 'Países Bajos',
    salary: '€2,300 - €2,500/mes',
    salaryPerHour: '€14.40/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Experiencia en conducción de EPT, camiones de recogida, o disposición para certificarse',
      'Abierto a trabajar en diferentes turnos',
      'Buena condición física',
      'No se requiere experiencia previa, pero es una ventaja si has trabajado en almacén antes',
      'Buenas habilidades de comunicación en inglés y/o neerlandés',
    ],
    benefits: [
      'Pagos semanales cada martes',
      'Reclutamiento online con proceso simple y mínimas formalidades',
      'Seguro médico',
      'Contrato de trabajo bajo ley neerlandesa con horas garantizadas',
      'Alojamiento organizado y transporte al trabajo si lo necesitas',
      'Soporte 24/7 por nuestro centro de servicio',
      'Acceso a la app myOTTO con horario de trabajo, recibos de pago y preguntas frecuentes',
      'Pago extra por trabajar en las tardes, noches y fines de semana',
      'Múltiples ubicaciones para elegir',
    ],
    description: 'Ofrecemos una variedad de servicios, manejando todo desde ropa y electrónicos hasta artículos del hogar y productos médicos. Con muchas ubicaciones en los Países Bajos, es un excelente lugar para aprender, ganar experiencia y desarrollar tu carrera. Puedes elegir trabajar en múltiples ciudades. Como empleado de almacén, serás responsable de completar y preparar pedidos para envío. Tus tareas incluirán recolección de productos con sistema de picking manual o por voz, carga y descarga de camiones con cuidado de los artículos, organización de productos en el almacén y mantenerlo limpio, conducción de EPT u otros camiones eléctricos, preparación de mercancías para envío y etiquetado correcto de paquetes.',
    available: true,
    urgent: false,
  },
  {
    id: 'job-015',
    title: 'Operario de Almacén de Productos Alimentarios',
    company: 'Centro de Distribución Alimentaria Especializada',
    location: 'Dordrecht',
    country: 'Países Bajos',
    salary: '€2,400 - €2,600/mes',
    salaryPerHour: '€14.76/hora',
    contractType: 'Tiempo completo',
    duration: '6 meses (renovable)',
    requirements: [
      'Pasaporte europeo vigente',
      'Experiencia conduciendo EPT o montacargas, o disposición para certificarse',
      'Abierto a trabajar diferentes turnos',
      'Buena condición física',
      'Disposición para trabajar en diferentes temperaturas',
      'Posesión de licencia de conducir categoría B',
      'Buenas habilidades de comunicación en inglés, polaco y/o neerlandés',
    ],
    benefits: [
      'Pagos semanales cada martes',
      'Reclutamiento online con proceso simple y mínimas formalidades',
      'Seguro médico',
      'Contrato de trabajo temporal bajo ley neerlandesa con horas garantizadas',
      'Alojamiento organizado y transporte al trabajo si lo necesitas',
      'Soporte telefónico 24/7 por nuestro centro de servicio',
      'App myOTTO con horario de trabajo, recibos de pago y preguntas frecuentes',
      'Horario estable de lunes a viernes',
      'Bonos adicionales por trabajo los sábados',
      'Trabajo en dos secciones: temperatura ambiente y productos frescos',
    ],
    description: 'Somos una empresa líder en la industria alimentaria. Ofrecemos muchos productos de alta calidad y nos enfocamos en nuevas ideas para mantener a los clientes felices. Nuestro equipo está comprometido a ofrecer un gran servicio y comida fresca y sabrosa. Tus tareas incluirán recolección de pedidos usando un sistema de picking por voz, clasificación y escaneo de productos usando equipos de escaneo para rastrear productos en el sistema, empaque de productos y preparación de pedidos para envío, levantamiento de paquetes de diferentes pesos, conducción de EPT u otros camiones eléctricos, carga de pallets en camiones para entrega y descarga de envíos entrantes.',
    available: true,
    urgent: false,
  },
  // ============================================
  // PARA AGREGAR UNA NUEVA OFERTA:
  // 1. Copia el objeto de arriba
  // 2. Pega aquí abajo
  // 3. Cambia todos los datos
  // 4. Cambia el 'id' a un número único (job-003, job-004, etc.)
  // ============================================
]


